/**
 * Mir Zinger Chicken — menu source of truth for menu.html
 * Edit sections/items here; the page renders from this data.
 */
window.MIR_ZINGER_MENU = {
  housePicks: [
    { name: "Zinger Burger", price: "$7.99", note: "Crispy chicken, signature sauce, brioche bun", sectionId: "zinger-sandwiches", badge: "Top pick", image: "https://slicecity.ca/wp-content/uploads/2025/08/Zinger-Burger-Spotlight_-Why-Its-More-Than-Just-a-Bite-scaled.png", alt: "Zinger Burger with crispy chicken" },
    { name: "Zinger Burger Combo", price: "$11.99", note: "Burger, fries & pop", sectionId: "zinger-sandwiches", badge: "Combo", image: "assets/zinger-burger-combo-hero.png", alt: "Burger combo with fries" },
    { name: "Chicken Biryani", price: "$11.99", note: "Aromatic basmati & spiced chicken", sectionId: "indian-cuisine", badge: "Fan fave", image: "https://media.istockphoto.com/id/2164869598/photo/kacchi-biryani-bronze-dish.jpg?s=612x612&w=0&k=20&c=lmFccYRb5rI6yXkhNAtMoVFnVk0g7i7e4lu_VSH7aIw=", alt: "Chicken biryani in a serving dish" },
    { name: "Butter Chicken", price: "$11.99", note: "Creamy tomato sauce · rice or naan", sectionId: "indian-cuisine", badge: "Best seller", image: "https://media.istockphoto.com/id/1411524598/photo/chicken-tikka-masala-cooked-marinated-chicken-in-spiced-curry-sauce.jpg?s=612x612&w=0&k=20&c=3JLbYigOnTQm-4exK-7uKeI3YoR0g9HxAkjxmuVmfpY=", alt: "Butter chicken in rich sauce" },
    { name: "Popcorn Chicken", price: "$6.99", note: "Bite-sized crunch", sectionId: "popcorn", badge: "Snack", image: "assets/popcorn-chicken.png", alt: "Crispy popcorn chicken pieces" },
    { name: "Original Poutine", price: "$6.99", note: "Curds & gravy", sectionId: "poutines", badge: "Canadian classic", image: "assets/original-poutine.png", alt: "Original poutine with fries and gravy" },
  ],
  navGroups: [
    { label: "Chicken & combos", ids: ["family-deals", "meal-deals", "two-can-dine", "family-combos", "tenders", "chicken-wings", "nuggets", "popcorn"] },
    { label: "Burgers & sandwiches", ids: ["zinger-sandwiches"] },
    { label: "Snacks & express", ids: ["zinger-express"] },
    { label: "South Asian", ids: ["indian-cuisine"] },
    { label: "Sides & poutines", ids: ["side-orders", "poutines"] },
    { label: "Specials & more", ids: ["everyday-specials", "drinks", "catering", "saturday-specials"] },
  ],
  nav: [
    { id: "family-deals", label: "Family Deals" },
    { id: "meal-deals", label: "Meal Deals" },
    { id: "two-can-dine", label: "2 Can Dine" },
    { id: "family-combos", label: "Family Combos" },
    { id: "tenders", label: "Tenders" },
    { id: "chicken-wings", label: "Wings" },
    { id: "nuggets", label: "Nuggets" },
    { id: "popcorn", label: "Popcorn" },
    { id: "zinger-sandwiches", label: "Zinger Sandwiches" },
    { id: "zinger-express", label: "Zinger Express" },
    { id: "indian-cuisine", label: "Indian Cuisine" },
    { id: "side-orders", label: "Side Orders" },
    { id: "everyday-specials", label: "Everyday Specials" },
    { id: "poutines", label: "Poutines" },
    { id: "drinks", label: "Drinks" },
    { id: "catering", label: "Catering" },
    { id: "saturday-specials", label: "Saturday Specials" },
  ],
  sections: [
    {
      id: "family-deals",
      tier: "flagship",
      title: "Family Deals",
      subtitle: "Big value. Big crunch. Perfect for the table.",
      items: [
        { name: "8 pcs Chicken", price: "$24.99", description: "Tender fried chicken pieces." },
        { name: "12 pcs Chicken", price: "$31.99", description: "Feed the crew." },
        { name: "16 pcs Chicken", price: "$41.99", description: "Our largest chicken bundle." },
      ],
    },
    {
      id: "meal-deals",
      tier: "flagship",
      title: "Meal Deals",
      subtitle: "Each meal includes regular fries & a soft drink.",
      items: [
        { name: "2 pcs Meal", price: "$11.99" },
        { name: "3 pcs Meal", price: "$13.50" },
        { name: "4 pcs Meal", price: "$14.99" },
      ],
    },
    {
      id: "two-can-dine",
      tier: "standard",
      title: "2 Can Dine",
      subtitle: "Share the crunch — built for two.",
      items: [
        {
          name: "2 Can Dine Deal",
          price: "$22.99",
          description: "5 pcs chicken, 2 regular sides & 2 pops.",
          tags: ["combo"],
        },
      ],
    },
    {
      id: "family-combos",
      tier: "standard",
      title: "Family Combos",
      subtitle: "Chicken, hearty sides & biscuits — one order, full table.",
      items: [
        { name: "8 pcs + 1 Large Side + 4 Biscuits", price: "$31.99" },
        { name: "12 pcs + 2 Large Sides + 4 Biscuits", price: "$45.99" },
        { name: "16 pcs + 3 Large Sides + 8 Biscuits", price: "$56.99" },
      ],
    },
    {
      id: "tenders",
      tier: "standard",
      title: "Tenders",
      subtitle: "Golden strips — dip, crunch, repeat.",
      items: [
        { name: "3 pcs", price: "$8.99" },
        { name: "3 pcs Combo", price: "$10.99", tags: ["combo"], description: "With fries & pop." },
        { name: "5 pcs", price: "$12.99" },
        { name: "5 pcs Combo", price: "$14.99", tags: ["combo"], description: "With fries & pop." },
      ],
    },
    {
      id: "chicken-wings",
      tier: "compact",
      title: "Chicken Wings",
      subtitle: "Juicy, saucy, satisfying.",
      items: [{ name: "1 lb Wings", price: "$9.99", description: "One pound of wings." }],
    },
    {
      id: "nuggets",
      tier: "standard",
      title: "Nuggets",
      subtitle: "Snackable crunch in every bite.",
      items: [
        { name: "6 pcs", price: "$6.99" },
        { name: "6 pcs Combo", price: "$9.99", tags: ["combo"], description: "With fries & pop." },
        { name: "9 pcs", price: "$9.99" },
        { name: "9 pcs Combo", price: "$12.99", tags: ["combo"], description: "With fries & pop." },
      ],
    },
    {
      id: "popcorn",
      tier: "standard",
      title: "Popcorn",
      subtitle: "Little pieces, big flavour.",
      items: [
        {
          name: "Popcorn Chicken",
          price: "$6.99",
          description: "Crispy bite-sized chicken.",
          tags: ["popular"],
        },
      ],
    },
    {
      id: "zinger-sandwiches",
      tier: "flagship",
      title: "Zinger Sandwiches",
      subtitle: "Crispy fillets, fresh toppings & soft buns.",
      items: [
        {
          name: "Zinger Burger",
          price: "$7.99",
          description: "Signature crispy chicken, sauce & lettuce on a brioche bun.",
          tags: ["popular", "bestseller"],
        },
        { name: "Zinger Burger Combo", price: "$11.99", tags: ["combo"], description: "Burger with regular fries & pop." },
        { name: "Fish Burger", price: "$8.49", description: "Breaded fish fillet on a bun." },
        { name: "Fish Combo", price: "$11.99", tags: ["combo"], description: "With fries & pop." },
        { name: "Beef Burger", price: "$6.99" },
        { name: "Beef Combo", price: "$9.99", tags: ["combo"], description: "With fries & pop." },
        { name: "Jr. Burger", price: "$3.99", description: "Smaller appetite, same quality." },
      ],
    },
    {
      id: "zinger-express",
      tier: "standard",
      title: "Zinger Express",
      subtitle: "Fast bites when you’re on the go.",
      items: [
        { name: "Torpedo Shrimps", price: "$9.99" },
        { name: "Fish & Chips + Pop", price: "$12.99", tags: ["combo"] },
        { name: "Breaded Mushrooms", price: "$6.99" },
        { name: "Fried Pickles", price: "$6.99" },
        { name: "Jalapeño Poppers", price: "$7.99" },
        { name: "Popcorn Chicken Bowl", price: "$6.99", description: "Popcorn chicken served bowl-style." },
      ],
    },
    {
      id: "indian-cuisine",
      tier: "flagship",
      title: "Indian Cuisine",
      subtitle: "Halal-certified South Asian favourites — spices, grills & comfort classics.",
      items: [
        {
          name: "Chicken Biryani",
          price: "$11.99",
          description: "Fragrant basmati rice layered with spiced chicken.",
          tags: ["halal"],
        },
        { name: "Chicken Tikka", price: "$8.99", description: "Marinated grilled chicken.", tags: ["halal"] },
        { name: "Paneer Tikka", price: "$8.99", description: "Grilled paneer with spices." },
        {
          name: "Paneer Tikka with Naan",
          price: "$11.99",
          description: "Paneer tikka served with fresh naan.",
        },
        { name: "Chicken Nihari w/ Naan", price: "$11.99", description: "Slow-cooked stew with naan.", tags: ["halal"] },
        { name: "Masala Kabob w/ Naan", price: "$9.99", description: "Spiced kabob with naan.", tags: ["halal"] },
        {
          name: "Butter Chicken w/ Rice or Naan",
          price: "$11.99",
          description: "Tender chicken in a rich, creamy tomato sauce — your choice of rice or naan.",
          tags: ["bestseller", "halal"],
        },
        { name: "1 lb Veggie Pakora", price: "$7.49", description: "Crispy mixed vegetable fritters." },
        { name: "Samosa Chaat", price: "$7.99", description: "Chickpeas, chutneys & crushed samosa." },
        { name: "Masala Chickpeas", price: "$5.99", description: "Chickpeas in aromatic masala." },
        { name: "Plain Rice", price: "$4.75" },
        { name: "Garlic Naan", price: "$2.49", description: "Soft naan brushed with garlic." },
        { name: "Vegetable Samosa", price: "$1.25", description: "Crispy pastry with spiced potato & peas." },
        { name: "Chicken or Beef Samosa", price: "$1.50", description: "Each.", tags: ["halal"] },
      ],
    },
    {
      id: "side-orders",
      tier: "standard",
      title: "Side Orders",
      subtitle: "Regular $3.99 · Large $6.99",
      items: [
        { name: "Fries", price: "$3.99 / $6.99", description: "Regular or large." },
        { name: "Onion Rings", price: "$3.99 / $6.99" },
        { name: "Gravy", price: "$3.99 / $6.99" },
        { name: "Macaroni Salad", price: "$3.99 / $6.99" },
        { name: "Mashed Potatoes", price: "$3.99 / $6.99" },
        { name: "Coleslaw", price: "$3.99 / $6.99" },
      ],
    },
    {
      id: "everyday-specials",
      tier: "accent",
      title: "Everyday Specials",
      subtitle: "Daily value picks from the kitchen.",
      items: [
        { name: "Fish Pakora", price: "$11.99" },
        { name: "Masala Kabab w/ Naan", price: "$9.99", tags: ["halal"] },
        { name: "Masala Chickpea w/ Rice or Naan", price: "$8.99" },
        { name: "Pakora Curry w/ Rice", price: "$8.99" },
      ],
    },
    {
      id: "poutines",
      tier: "accent",
      title: "Poutines",
      subtitle: "Fries, curds & gravy — plus a house twist.",
      items: [
        { name: "Original Poutine", price: "$6.99", description: "Classic fries, cheese curds & gravy.", tags: ["popular"] },
        { name: "Butter Chicken Poutine", price: "$8.49", description: "Topped with butter chicken gravy-style sauce." },
      ],
    },
    {
      id: "drinks",
      tier: "compact",
      title: "Drinks",
      subtitle: "Soft drinks & more — included with meal deals.",
      items: [
        {
          name: "Soft drinks & bottled beverages",
          price: "—",
          description: "Selection varies — add a pop to any combo or ask when you order.",
        },
      ],
    },
    {
      id: "catering",
      tier: "compact",
      title: "Catering Specials",
      subtitle: "Offices, parties & gatherings — we’ll help you size it right.",
      items: [
        { name: "10 People Package", price: "$150" },
        { name: "15 People Package", price: "$200" },
      ],
    },
    {
      id: "saturday-specials",
      tier: "accent",
      title: "Saturday Specials",
      subtitle: "Weekend-only favourites — 11 a.m. to 2 p.m.",
      items: [
        {
          name: "Saturday: Piya Nihari (Beef or Goat)",
          price: "$18.99",
          description: "Traditional slow-cooked nihari.",
          tags: ["halal"],
        },
        { name: "Saturday: Puri Choley", price: "$8.99", description: "Fluffy puri with spiced chickpeas." },
      ],
    },
  ],
};
